options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['composer', 'environments', 'storage', 'dags', 'update', '--environment', 'data-pipeline-orchestrator', '--location', 'us-central1', '--source', './dags/']
